### ISSUE TITLE
support for parallel_tests

### ISSUE THREAD

**Issue by aaronjensen** [codeclimate/ruby-test-reporter#10]
I noticed there's support for tddium's parallel builds, is there also support for the parallel_tests gem? I haven't had a chance to try it yet, so feel free to consider this issue a request for documentation if there already is :)

**Comment by sguha00** [comment]
Does this fix work on CircleCI?

**Comment by aaronjensen** [comment]
@sguha00 no, it wouldn't. CircleCI runs the tests on different machines. There may be another way to aggregate them, but I don't know it. You could probably model it after the tddium parallelized build support: https://github.com/codeclimate/ruby-test-reporter/commit/31432b8944c3ba50b71bf1f1d545949b51cca4c3

**Comment by evanwhalen** [comment]
Run [this script](https://gist.github.com/evanwhalen/f74879e0549b67eb17bb) as part of the circle ci build process. The script will merge the simplecov results, format to html and also post to codeclimate.

Add the following to circle.yml (assuming the script path is `script/circle`)

```yaml
test:
  post:
    - bundle exec script/circle
```

**Comment by iamnader** [comment]
@evanwhalen what does your spec helper look like?  are you using the codeclimate reporter:
```
  require "codeclimate-test-reporter"
  CodeClimate::TestReporter.start
```
or SimpleCov directly?

Thanks!

**Comment by evanwhalen** [comment]
@iamnader the spec helper only reference simplecov and not code climate test reporter. The aforementioned script merges the results generated by simplecov and posts them to code climate.

```ruby
require 'simplecov'

if ENV['CIRCLE_ARTIFACTS']
  dir = File.join("..", "..", "..", ENV['CIRCLE_ARTIFACTS'], "coverage")
  SimpleCov.coverage_dir(dir)
end
```

**Comment by iamnader** [comment]
Thanks @evanwhalen 

Isn't ENV["CIRCLE_ARTIFACTS"] an absolute path?  Why do you use: "..", "..", ".."  ?
