### ISSUE TITLE
coverage is 100% when test fails

### ISSUE THREAD

**Issue by franklingu** [codeclimate/ruby-test-reporter#103]
recently I have this output when running spec

~~~
Web Console is activated in the test environment, which is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
~~~

But the reported test coverage is 100%

**Comment by pbrisbin** [comment]
Would it be possible for you to see if you get the same behavior using simplecov directly?

**Comment by franklingu** [comment]
if you need the output, I will replicate the error and paste it here. but basically simeplecov shows 20%, like 20+ lines out of 100+ lines--I guess it is because simplecov stopped after loading some initialization file?

**Comment by pbrisbin** [comment]
Very strange. I asked because we really just run simplecov with a custom formatter, which I wouldn't expect to change the percentage reported, even in edge cases like this.

I'll have to dig deeper to determine what's going on. Thanks for the report.

**Comment by franklingu** [comment]
```
Coverage report generated for RSpec to /home/junchao/Desktop/repos/nusskylab/coverage. 29 / 144 LOC (20.14%) covered.
```

for your ref. :)

**Comment by aleksandra-stolyar** [comment]
I have the same problem, but code climate also started including vendor components issues and decreasing my gpa.

**Comment by pbrisbin** [comment]
> but code climate also started including vendor components issues and decreasing my gpa

Hi @aleksandra-stolyar, that sounds like a separate issue unrelated to test coverage reporting. Maybe the codeclimate/codeclimate repository is a better place to report that? Please include the file names the issues are being reported on, as well as your full `.codeclimate.yml`.

**Comment by dblandin** [comment]
Hey @franklingu,

We've made some improvements to the ruby test reporter that should address the inconsistencies you reported.

The new version requires a different invocation style. You can find the upgrade documentation [here](https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions).

**Comment by pbrisbin** [comment]
Going to go ahead and close, since we believe this is fixed in the new version. Please re-open if this is still an issue. Thanks!
