### ISSUE TITLE
Travis fails with empty load with minimal example

### ISSUE THREAD

**Issue by lmrodriguezr** [codeclimate/ruby-test-reporter#106]
I have a [relatively large repository](https://github.com/bio-miga/miga), but the test set is really minimal. A very simple [`Rakefile`](https://github.com/bio-miga/miga/blob/3c69e458dea6589b9bf59d2630e9e380e37d42ef/Rakefile):
```ruby
require "rake/testtask"

$:.unshift File.join(File.dirname(__FILE__), "lib")

SOURCES = FileList["lib/**/*.rb"]

desc "Default Task"
task :default => :test

Rake::TestTask.new do |t|
   t.libs << "test"
   t.pattern = "test/*_test.rb"
   t.verbose = true
end
```

With a simple [`test_helper.rb`](https://github.com/bio-miga/miga/blob/3c69e458dea6589b9bf59d2630e9e380e37d42ef/test/test_helper.rb):
```ruby
require "codeclimate-test-reporter"
CodeClimate::TestReporter.start

require "rubygems"
require "test/unit"
require "miga/version"
```

And just [one test](https://github.com/bio-miga/miga/blob/3c69e458dea6589b9bf59d2630e9e380e37d42ef/test/version_test.rb):
```ruby
require "test_helper"

class VersionTest < Test::Unit::TestCase
  
  def test_version
    assert_respond_to(MiGA::MiGA, :VERSION)
    assert_respond_to(MiGA::MiGA, :CITATION)
    assert_equal(MiGA::VERSION.first, MiGA::MiGA.VERSION)
  end
  
end
```

It's very similar to tests I've deployed in other repos, but this one simply won't stop giving me an [empty payload error](https://travis-ci.org/bio-miga/miga/builds/118607549#L189) when reporting to code climate. Could this be a bug in the reporter?

Thanks!

**Comment by GordonDiggs** [comment]
@lmrodriguezr Can you paste the output of running the tests?

**Comment by lmrodriguezr** [comment]
BTW, I saw other similar reports (#32 and #94), that seemed to be caused by loading rails before starting the coverage, but I'm not even using rails. In fact, I only load `rake/testtask` in my `Rakefile`, and `codeclimate-test-reporter`, `rubygems`, `test/unit`, and `miga/version` (which, in turn, loads `date`) in my `test_helper.rb`, and that's all I load from within my only test :-/

I've been trying to tweak the files here and there, but I'm out of ideas since it's such a small test set.

Thanks!

**Comment by lmrodriguezr** [comment]
Wow! The "downside" is not much of a problem, `version` doesn't really have anything important to be covered, I was just using it to start deploying.

Thanks a lot!
