### ISSUE TITLE
Configuration for gem development

### ISSUE THREAD

**Issue by EdDeAlmeidaJr** [codeclimate/ruby-test-reporter#123]
I'm a Code Climate user and my configuration for apps works fine when I do it "by the book", adding

```ruby
$ gem "codeclimate-test-reporter", group: :test, require: nil
```
to Gemfile and so on.

But now I'm trying to add code coverage for a gem repository and, of course, my Gemfile is only

```ruby
source 'https://rubygems.org'
gemspec
```

indicating I'm using .gemspec file to define my gems for development and runtime.

How do I define this **group: :test** thing when doing gem development?

**Comment by Shwetakale** [comment]
@EdDeAlmeidaJr I haven't done it before but I don't think you need to do anything extra by adding it in test group of ```Gemfile``` should work and you will need to add dependency in ```gemspec```. I also checked how other gems do this and saw they also add it in test group. For ex see [this](https://github.com/mongoid/mongoid-slug/blob/master/Gemfile) Gemfile. Would like to know if there is any other way of doing same thing.

**Comment by EdDeAlmeidaJr** [comment]
I'll do some tests to see if there is another way. It worked fine when I started using a Gemfile, just like in any other development, and only used my .gemspec file to development dependencies.

**Comment by dblandin** [comment]
Hey @EdDeAlmeidaJr,

If you are working on a gem with a `.gemspec` file, you can add the reporter as a development dependency:

```ruby
Gem::Specification.new do |spec|
  # ...
  spec.add_development_dependency "simplecov"
  spec.add_development_dependency "codeclimate-test-reporter"
end
```

**Comment by EdDeAlmeidaJr** [comment]
Thanks @dblandin!
