### ISSUE TITLE
Different coverage report in case of code-climate and TravisCI

### ISSUE THREAD

**Issue by BandanaPandey** [codeclimate/ruby-test-reporter#126]
I am using followings in my app::

**codeclimate-test-reporter 0.6.0
simplecov 0.12.0**

I am seeing this that **travis** and **codeclimate** shows different code coverage that is
travis shows 57.7% whereas codeclimate shows 54.3%. I am not sure whether this is an issue or not.
Any thoughts?

**Comment by efueger** [comment]
Hey @BandanaPandey - are you seeing that for your default branch coverage in the UI, or with the browser extension in GitHub?

There could be a couple of things happening, including things like [parallel or multiple runs](https://docs.codeclimate.com/docs/test-coverage-troubleshooting-tips#section-sending-multiple-payloads-per-commit).

Can you drop a line with your repo details (and link for the page where you're seeing that coverage) at www.codeclimate.com/help? Happy to take take a closer look.

**Comment by BandanaPandey** [comment]
@efueger this is what I am getting on running testcases locally::
```
Run options: --seed 17592

# Running:

S..............S...................S..............................................S...............S...............SS......................SS.S.....S.SE.........S..........................S.......E.S..S...

Fabulous run in 21.681041s, 9.4091 runs/s, 11.8998 assertions/s.
204 runs, 258 assertions, 0 failures, 2 errors, 16 skips

You have skipped tests. Run with --verbose for details.
Coverage report generated for MiniTest to /home/bandana/code_curiosity/code-curiosity/coverage. 970 / 1587 LOC (61.12%) covered.
```
But on [TravisCI](https://travis-ci.org/BandanaPandey/code-curiosity/builds/163633467), I am getting Coverage = 60.74%.

Any idea why is this happening??

**Comment by dblandin** [comment]
Hey @BandanaPandey,

We've made some improvements to the ruby test reporter that should address the inconsistencies you reported.

The new version requires a different invocation style. You can find the upgrade documentation [here](https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions).

Thanks!

**Comment by BandanaPandey** [comment]
:+1:  @dblandin thanks .
