### ISSUE TITLE
Support for older version of ruby

### ISSUE THREAD

**Issue by amitrai99** [codeclimate/ruby-test-reporter#131]
I can't find any documentation that explains the version of ruby this gem supports.

**Comment by dblandin** [comment]
You can find the Ruby version depedency within the gemspec [here](https://github.com/codeclimate/ruby-test-reporter/blob/master/codeclimate-test-reporter.gemspec#L16).

At the moment this gem supports ruby versions >= 1.9.

**Comment by dblandin** [comment]
In case you're also trying to run a `bundle install` for this project, there was some work done recently to make the development dependencies 1.9 compatible: https://github.com/codeclimate/ruby-test-reporter/pull/132

I'm going to go ahead and close this issue. Let us know if you have any other questions. Thanks!
