### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by 1v** [codeclimate/ruby-test-reporter#142]
https://codeclimate.com/repos/57f7da915b814a5940000aaf/coverage_setup
```
require "simplecov"
SimpleCov.start" <- remove
```

**Comment by pbrisbin** [comment]
Are you sure? https://github.com/colszowka/simplecov#getting-started shows that content.

**Comment by maxjacobson** [comment]
@pbrisbin I shipped ruby-test-reporter 1.0.0 on Friday, which included updating the in-app docs. It looks like I accidentally added an extra `"` there. Making a fix now. Thanks for the head's up @1v

**Comment by pbrisbin** [comment]
Ah it was just the quote. Sorry, I missed that and thought removing the whole line was the suggestion.
