### ISSUE TITLE
Custom SimpleCov coverage_dir not supported

### ISSUE THREAD

**Issue by dueckes** [codeclimate/ruby-test-reporter#143]
Gem version: 1.0.1

The reporter does not appear to recognise a custom SimpleCov coverage directory.

I often use a configuration such as this to consolidate my generated artifacts under one directory:
```ruby
SimpleCov.start do
  coverage_dir "tmp/coverage"
end
```

When I run the reporter using this configuration, here's the error I'm seeing:
```
Coverage report generated for RSpec to /my/project/tmp/coverage. 35 / 35 LOC (100.0%) covered.

bundle exec codeclimate-test-reporter

Coverage results not found

rake aborted!

Command failed with status (1): [bundle exec codeclimate-test-reporter...]
```

Any chance there is support for customising this directory (current or planned)?

**Comment by dblandin** [comment]
Hey @dueckes,

Yep! Supporting an alternate coverage directory makes sense to me. At the moment it's hard-coded to `./coverage`, but we should definitely support alternate locations via a flag on the binary. Would something like the following work for you?

```bash
$ codeclimate-test-reporter --directory /tmp/coverage
```

**Comment by dueckes** [comment]
That would work.

It would be ideal to have it inferred from SimpleCov settings, but given the hard separation of the reporter from SimpleCov / running the tests, repeating the directory seems appropriate.
