### ISSUE TITLE
Following the upgrade instructions leads to LoadError

### ISSUE THREAD

**Issue by awendt** [codeclimate/ruby-test-reporter#150]
Hi,

after 1.0.3 is out, I've attempted to upgrade from 0.6.0 again ([here's what I changed](https://gist.github.com/awendt/72c6ee952f280c52066250565b8275fb)), and Travis runs into this error:

    spec/codeclimate_helper.rb:3:in `<top (required)>': uninitialized constant CodeClimate (NameError)

I've successfully reproduced this locally. Here's a transcript of my debugging session:

```
[1] pry(main)> CodeClimate
NameError: uninitialized constant CodeClimate
from (pry):1:in `<top (required)>'
<snip>
[4] pry(main)> require 'codeclimate-test-reporter'
=> true
[5] pry(main)> CodeClimate
=> CodeClimate
```

This seems to indicate that despite [what's documented for the upgrade](https://github.com/codeclimate/ruby-test-reporter/blob/276a24124afc8a7c0abf63c96cde185fb6a2dd8e/README.md#upgrading-from-pre-10-versions), I still need this line in my `spec/codeclimate_helper.rb`:

```ruby
require 'codeclimate-test-reporter'
```

Do you agree with this?

**Comment by pbrisbin** [comment]
It looks like your `spec/codeclimate_helper.rb` is referencing `CodeClimate` at line 3. It shouldn't do this.

Post-1.0, the reporter runs entirely outside your test suite, as its own executable. That means your own code should never reference it, or even know it exists*; it should just load and run Simplecov normally. Then you should invoke the reporter as a new step in your build.

*it's only present in the Gemfile so it'll be installed in your bundle -- and even this is not necessary if you'd prefer to `gem install` it separately.

**Comment by anthony-robin** [comment]
@pbrisbin Thanks for the explanation but I'm not sure to understand everything:

> Then you should invoke the reporter as a new step in your build

How can I do that in a `travis.yml` file ? 
I guess the travis [documentation](https://docs.travis-ci.com/user/code-climate/#Measuring-Test-Coverage-with-Code-Climate) is not up to date yet and I feel lost with this new way to process.

**Comment by maxjacobson** [comment]
Hey @anthony-robin. Yep, sorry about that. We have [a PR](https://github.com/travis-ci/docs-travis-ci-com/pull/794/files) open to update those docs.

You can do it like this:

```yaml
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: adf08323...
```

**Comment by anthony-robin** [comment]
@maxjacobson Thanks, that was an easy fix !
