### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by amilligan** [codeclimate/ruby-test-reporter#152]
We would appreciate it.

**Comment by maxjacobson** [comment]
Thanks, I agree that's a good idea.

We have a section in our README which outlines the upgrade process for transitioning between v0.6.0 and v1.x.x: https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions

But having it in a more formal document is a good convention that we're happy to follow. I'll try and add this soon
