### ISSUE TITLE
Support or older version of Ruby

### ISSUE THREAD

**Issue by amitrai99** [codeclimate/ruby-test-reporter#155]
Is it possible to use a possibly an older version of this Gem to support old rails project that is still on Ruby 1.87?

**Comment by pbrisbin** [comment]
@amitrai99 sorry but I'm not sure how or if it would work to use an older version of this gem to get 1.8.7 support. If you were to try and checkout/install older tags and found one that worked for 1.8.7, please feel free to report that back on this Issue for others to find.
