### ISSUE TITLE
Bundler fails to load the codeclimate-test-reporter command

### ISSUE THREAD

**Issue by alvinkatojr** [codeclimate/ruby-test-reporter#166]
I have followed the upgrade instructions listed in the [change log](https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03) but keep running into the error shown below whenever I run ```bundle exec codeclimate-test-repoter``` with my token as specified in the last step in the code climate ruby sections [docs](https://docs.codeclimate.com/docs/ruby). 

My system's gems are up to date so this error does n't make sense to me at the moment. 

![screen shot 2017-01-05 at 00 33 55](https://cloud.githubusercontent.com/assets/519988/21660146/466e1d98-d2df-11e6-8837-ca5396530f6c.png)

**Comment by maxjacobson** [comment]
Hi @alvinkatojr 

The relevant line here is:

```
RuntimeError: HTTP Error: 401
```

Will you double check that your token is correct? This error means that we couldn't find a repo in our system that corresponds to the provided token.

**Comment by alvinkatojr** [comment]
Hi @maxjacobson, 

I just generated a fresh token and still keep getting the same error. Is n't this the proper [url](https://codeclimate.com/profile/tokens) for token generation?

**Comment by maxjacobson** [comment]
@alvinkatojr Ah, that explains it. It's actually not. Those tokens are used to authenticate requests made to [the Code Climate API](https://docs.codeclimate.com/docs/api). The token used by the test reporter is used to identify which repo you're sending a report for. You can find the token by visiting your repo's settings on Code Climate then clicking on the "Test Coverage" section.

**Comment by maxjacobson** [comment]
@alvinkatojr btw - given that the personal access token identifies you to the API, I recommend revoking any personal access token that gets shared publicly on [the tokens page](https://codeclimate.com/profile/tokens). The repo token is safe to share publicly.

**Comment by alvinkatojr** [comment]
@maxjacobson Just revoked all my personal access tokens so am safe on that end.

**Comment by alvinkatojr** [comment]
@maxjacobson Oh and finally found where that repo token, success! Thanks for helping out. 

Also finding my personal access token itself was war, it would be awesome if you or anyone else on the team could add this snippet of "where to find the repo token" to the docs. It'll save a lot of headaches ;)

**Comment by maxjacobson** [comment]
@alvinkatojr Thanks for that feedback, we agree. Working on an update now.

In the meantime, going to close this out. Let me know if anything else comes up
