### ISSUE TITLE
Regression in v1.0.4?

### ISSUE THREAD

**Issue by matiaskorhonen** [codeclimate/ruby-test-reporter#174]
The changes from #163 seem to be causing some issues for us. At the end of every test run we get this error message:

```
Coverage report generated for RSpec to /home/travis/build/kiskolabs/app/coverage. 5183 / 10974 LOC (47.23%) covered.
Formatter CodeClimate::TestReporter::Formatter failed with NoMethodError: undefined method `map' for #<SimpleCov::Result:0x000000180f2900>
Did you mean?  tap (/home/travis/build/kiskolabs/app/vendor/bundle/ruby/2.3.0/gems/codeclimate-test-reporter-1.0.5/lib/code_climate/test_reporter/formatter.rb:16:in `format')
```

* rails 4.2.7.1
* rspec 3.4
* simplecov 0.13.0
* codeclimate-test-reporter 1.0.5

**Comment by matiaskorhonen** [comment]
Ah, this was my fault; I hadn't read the upgrade notes :-\

**Comment by maxjacobson** [comment]
@matiaskorhonen glad you've got this working again! Please let us know if you run into any other issues.
