### ISSUE TITLE
Simplify execution for open-source projects

### ISSUE THREAD

**Issue by ioquatix** [codeclimate/ruby-test-reporter#179]
In my `.simplecov` I have:

```ruby
# Enable coveralls in travis:
if ENV['TRAVIS']
	require 'coveralls'
	Coveralls.wear!
end
```

All my projects essentially have the same line.

In my `Rakefile`, to kick testing off:

```ruby
RSpec::Core::RakeTask.new(:spec) do |task|
	begin
		require('simplecov/version')
		task.rspec_opts = %w{--require simplecov} if ENV['COVERAGE']
	rescue LoadError
            warn "Couldn't load simplecov for #{RUBY_VERSION}"
	end
end
```

And in `.travis.yml`:

```
env: COVERAGE=true
```

For completeness, my Gemfile is

```ruby
group :test do
	gem 'simplecov'
	gem 'coveralls', require: false
end
```

This is a very simple setup.

- Doesn't require per-project token (travis/coveralls figures it out).
- Minimal custom code, on the direct path of executing/testing.

I think this kind of setup is ideal. I have quite a few repos so the DRY principle, as much as is possible, is ideal.

**Comment by ioquatix** [comment]
Ideally, in .simplecov, it would be possible to have something like

```ruby
require 'codeclimate-test-reporter/simplecov' if ENV['TRAVIS']
```

Another option would be to explore using `.rspec`, e.g.

```ruby
--require codeclimate/coverage
```

And that sets everything up? Perhaps even just a local file, e.g. `spec/coverage.rb` which does it on a per-project basis.

**Comment by dblandin** [comment]
Hey @ioquatix ,

Thank for the issue!

As we're winding down development on this ruby-specific reporter, I'd recommend checking out our new test reporter and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉
