### ISSUE TITLE
v1.0.7 incompatible with simplecov 0.14.0

### ISSUE THREAD

**Issue by bliof** [codeclimate/ruby-test-reporter#180]
The gem doesn't work with the latest version of simplecov.

```
bundler: failed to load command: codeclimate-test-reporter (/opt/circleci/.rvm/gems/ruby-2.3.3/bin/codeclimate-test-reporter)
NoMethodError: undefined method `merge_resultset' for #<Hash:0x007f0e9fef8be8>
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:96:in `block in merge_results'
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:95:in `each'
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:95:in `merge_results'
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter/formatter.rb:24:in `format'
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/lib/code_climate/test_reporter.rb:19:in `run'
  /opt/circleci/.rvm/gems/ruby-2.3.3/gems/codeclimate-test-reporter-1.0.7/bin/codeclimate-test-reporter:21:in `<top (required)>'
  /opt/circleci/.rvm/gems/ruby-2.3.3/bin/codeclimate-test-reporter:22:in `load'
  /opt/circleci/.rvm/gems/ruby-2.3.3/bin/codeclimate-test-reporter:22:in `<top (required)>'
```

It will be worth to lock the dependency to a specific version that is supported (currently in the gemspec):

```
spec.add_runtime_dependency "simplecov"
```

### Relates to:
* 💎  https://github.com/colszowka/simplecov/tree/v0.14.0

**Comment by GordonDiggs** [comment]
Hey @bliof! Thanks for opening this issue. If you want to open a pull request, I'd happily merge it, but don't know when we will have time to address it. Additionally, we are starting work on a new test reporter (https://github.com/codeclimate/test-reporter) that will be ready soon and will replace this one. If you are interested in hearing when that is ready, we are tracking an issue [here](https://github.com/codeclimate/test-reporter/issues/24)!

**Comment by dblandin** [comment]
Looks like the update made in #181 rolled out with version [v1.0.8](https://rubygems.org/gems/codeclimate-test-reporter/versions/1.0.8) of the reporter yesterday.

Going to go ahead and close this issue. Thanks!
