### ISSUE TITLE
README Usage instructions are wrong.

### ISSUE THREAD

**Issue by cgriego** [codeclimate/ruby-test-reporter#184]
The README instructs the user to run the following:
```
CODECLIMATE_REPO_TOKEN=my_token bundle exec rspec && bundle exec codeclimate-test-reporter
```
However, the `CODECLIMATE_REPO_TOKEN` environment variable will only be exposed to the `bundle exec rspec` process and not to the `bundle exec codeclimate-test-reporter` process.

**Comment by dblandin** [comment]
@cgriego You're totally right! Good catch.

I've updated the README in #185. Thanks for the issue 👍
