### ISSUE TITLE
Ability to override TestReporter::PostResults.write_to_file?

### ISSUE THREAD

**Issue by jmcnevin** [codeclimate/ruby-test-reporter#186]
It appears as though Solano CI integration with this gem is currently broken.  I am able to configure a custom post-build hook in Solano that will execute `bundle exec codeclimate-test-reporter`, but a special rule in this method (`CodeClimate::TestReporter.tddium?`) will prevent that from actually posting the coverage results to CodeClimate.

There is support here to force the "write to file" behavior using environment variables, but no ability to force the opposite behavior.

**Comment by ale7714** [comment]
Hi @jmcnevin, this is a known issue on the latest versions of the reporter. `v0.6.0` works correctly with Solano. Additionally, we are working on a new unified test reporter (https://github.com/codeclimate/test-reporter) that will be in Beta soon and will replace this one. This new test reporter offers support to parallel tests.

**Comment by ale7714** [comment]
I'm going to close the issue but if you have more questions feel free to reopen it.
