### ISSUE TITLE
Error when CodeClimate site is on maintenance.

### ISSUE THREAD

**Issue by sublimecoder** [codeclimate/ruby-test-reporter#196]
I get a 405 and an exception thrown while code climate site is on maintenance. Shouldn't this fail gracefully with some warnings output to the console but not causing an outright failure?

**Comment by ale7714** [comment]
Hi @sublimecoder, Sorry for the trouble. This is something we have been discussing and hope to improve on our new [`test-reporter`](https://github.com/codeclimate/test-reporter). We recently shared some of those ideas here: https://github.com/codeclimate/test-reporter/issues/239#issuecomment-339051155.

**Comment by sublimecoder** [comment]
Ok awesome, thanks for the quick reply. It’s nice to know it’s a known issue with a potential solution soon. Not that Code Climate goes down for maintenance that often.

**Comment by ale7714** [comment]
@sublimecoder thanks for your understanding. Going to close this issue but if any other question comes up, don't hesitate to contact us.
