### ISSUE TITLE
Outdated version of simplecov

### ISSUE THREAD

**Issue by wagenet** [codeclimate/ruby-test-reporter#200]
This uses simplecov 0.13, but simplecov is now up to 0.16.

**Comment by wfleming** [comment]
This gem is deprecated, and we are no longer making updates to it. Please consider switching to [our new test reporter](https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage), which is not tied to any particular Simplecov version & will allow you to use whatever version of Simplecov is appropriate for you.

**Comment by wagenet** [comment]
Whoops! I made this change on one repo, but forgot to do it on this one.
