### ISSUE TITLE
Add support for sending multiple results per run or explicit pushing of test results

### ISSUE THREAD

**Issue by djohnsonjr** [codeclimate/ruby-test-reporter#24]
I sent this to Codeclimate in a support email, and they suggested that I open an issue here instead.

Setup/Backstory

We are using minitest, and when I run rake minitest, it actually executes rake tasks for each type of test that we have (unit, decorator, integration, etc).  That appears to cause our coverage results to get sent to Codeclimate at the end of each section, and Codeclimate only accepts the first one.

I tried a few different ways to only push results to code climate once.  This was as close as I got (from my email to Codeclimate):

I found that Coveralls deals with this problem in their documentation: https://coveralls.io/docs/ruby under the “Merging Multiple Test Suites” section.

That inspired me to do this in our Rakefile:

namespace :minitest do
  desc "Starts up code climate test reporter to send coverate to code climate"
  task :start_code_climate => :environment do
    require "codeclimate-test-reporter"
    CodeClimate::TestReporter.start
  end

  # We only want to send coverate to code climate on integrations tests.
  task :integration => [:start_code_climate]
end

So, now CodeClimate’s reporter is only getting started when our integration suite fires up.  That’s the last in our test suite. So, now we only send it one time because we only start it one time.

The down side that I found is that while Simplecov is accumulating results across my different test suites, it looks like the code climate reporter is only taking the results of the final suite results (not the accumulated results).

That can be seen in this test output.

Coverage report generated for Decorator Tests, Generator Tests, Integration Tests, Mailer Tests, Unit Tests to /home/rof/src/github.com/khorus/dev/coverage. 3748 / 3887 LOC (96.42%) covered.
Coverage = 87.68%. Sending report to https://codeclimate.com for branch master... done.

Real Question/Feature Request:

Is there a way that I can use this rake approach to only push the results at a specific time even though the reporter is started earlier (like the Coveralls approach)?

I looked around in the gem a little bit but I couldn’t find a way to do that.  I wasn’t sure if someone there would have more knowledge of how it works.

**Comment by grosser** [comment]
try the new merge PR https://github.com/codeclimate/ruby-test-reporter/pull/80 or https://github.com/grosser/cc-amend

**Comment by pbrisbin** [comment]
I've created a new Issue to consolidate this with the 2 other similar issues. Please continue discussion there.
