### ISSUE TITLE
Codeclimate test reporter sending wrong value when rspec fails/aborts

### ISSUE THREAD

**Issue by karthikvgupta** [codeclimate/ruby-test-reporter#40]
Using 0.3.0 of codeclimate-test-reporter, when rspec fails/gets aborted due to an error, it did send wrong coverage information to code climate. 
![skitch_1](https://cloud.githubusercontent.com/assets/5321440/3147841/6f8a5b86-ea59-11e3-8b8b-92544c53cd16.png)
It should ideally send either correct coverage value or nothing at all.

**Comment by jonathancadepowers** [comment]
Please feel free to re-open this one if anyone has ideas on ways to address this. Thanks!
