### ISSUE TITLE
Support for coverage merging for multiple travis builds

### ISSUE THREAD

**Issue by meeee** [codeclimate/ruby-test-reporter#49]
While #10 only concerned parallel_tests, I'd still be interested in merging the coverage results for multiple builds on Travis. Unlike parallel_tests, aggregation on filesystem-level is not possible with Travis as it isolates each build in seperate VMs or containers.

Until then, CodeClimate coverage reporting is useless for us (https://github.com/opf/openproject).

**Comment by JeanMertz** [comment]
:+1: to this. Has there been any developments since August last year?

**Comment by brodock** [comment]
:+1: we use codeclimate and circleci too and would like to have coverage aggregated. We saw that Coveralls recently release support for that.

**Comment by nj** [comment]
:+1: too, as it can make quite a big difference when comparing before and after parallelism.

**Comment by grosser** [comment]
try this: https://github.com/grosser/cc-amend

**Comment by JeanMertz** [comment]
@grosser I don't see how that could work, given that the builds run in their own isolated environments, without access to their respective file systems.

**Comment by grosser** [comment]
Every build sends the partial coverage report to cc-amend and cc-amend joins them and forwards them to code-climate.

**Comment by pbrisbin** [comment]
I've created a new Issue to consolidate this with the 2 other similar issues. Please continue discussion there.
