### ISSUE TITLE
Code coverage does not get reported locally unless `CODECLIMATE_REPO_TOKEN` is set

### ISSUE THREAD

**Issue by davidcelis** [codeclimate/ruby-test-reporter#61]
Hi! First off, really excited that CodeClimate now also shows test coverage. It's really useful, so thank you all for that!

One thing I'd love is if the ruby-test-reporter gem would report and output locally without needing to fudge with environment variables. IMO, local coverage would be a really useful default. I was working with an open source project today and wanted to submit a PR simply to improve test coverage. To do that well, I had to set `CODECLIMATE_REPO_TOKEN` locally. If I set it to a fake token, it seems to work fine until it attempts to POST the payload to CodeClimate:

```
% CODECLIMATE_REPO_TOKEN=no rspec
.......
Finished in 0.01519 seconds
7 examples, 0 failures
Coverage = 98.63%. Sending report to https://codeclimate.com for branch master... Code Climate encountered an exception: RuntimeError
HTTP Error: 401
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/codeclimate-test-reporter-0.4.3/lib/code_climate/test_reporter/client.rb:69:in `post_results'
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/codeclimate-test-reporter-0.4.3/lib/code_climate/test_reporter/formatter.rb:29:in `format'
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/simplecov-0.9.1/lib/simplecov/result.rb:46:in `format!'
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/simplecov-0.9.1/lib/simplecov/configuration.rb:158:in `block in at_exit'
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `call'
/Users/david/Documents/Code/git/emoruby/vendor/bundle/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

It would be great if only the submission to CodeClimate depended on the token being set. If not set, I'd still love for the coverage results to be printed to the Terminal and saved to the `coverage/` directory!

**Comment by jonathancadepowers** [comment]
@davidcelis Appreciate the feedback here (and sorry for the delay in getting back to you). I'll +1 this for you on our feature request board, for us to consider adding.

Until then though, I wanted to pass along some info to you on how to save the raw coverage data to disk (versus POSTing it to us): http://docs.codeclimate.com/article/220-help-im-having-trouble-with-test-coverage#raw_coverage_ruby

That's not exactly what you're looking for, but is hopefully still helpful. Thanks again.
