### ISSUE TITLE
Travis coverage and local so different

### ISSUE THREAD

**Issue by Strech** [codeclimate/ruby-test-reporter#73]
Project: https://github.com/Strech/pup

Local run results:

```
bundle exec rspec

Randomized with seed 25485
........*...............

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Pup::Rack::Shorten#shorten when url is malformed should eq 400
     # No reason given
     Failure/Error: pending { expect(response.status).to eq 400 }

       expected: 400
            got: 200

       (compared using ==)
     # ./spec/lib/pup/rack/shorten_spec.rb:34:in `block (4 levels) in <top (required)>'

Finished in 0.05266 seconds (files took 0.419 seconds to load)
24 examples, 0 failures, 1 pending

Randomized with seed 25485

Coverage report generated for RSpec to /media/psf/Develop/github/pup/coverage. 107 / 108 LOC (99.07%) covered.
I, [2015-02-06T21:15:36.884917 #6581]  INFO -- : Not rep
```

Travis CI run results: https://travis-ci.org/Strech/pup/jobs/49758982

```
3.03s$ bundle exec rspec
Randomized with seed 8718
.......................*
Pending: (Failures listed here are expected and do not affect your suite's status)
  1) Pup::Rack::Shorten#shorten when url is malformed should eq 400
     # No reason given
     Failure/Error: pending { expect(response.status).to eq 400 }
       
       expected: 400
            got: 200
       
       (compared using ==)
     # ./spec/lib/pup/rack/shorten_spec.rb:34:in `block (4 levels) in <top (required)>'
Finished in 0.08671 seconds (files took 0.32152 seconds to load)
24 examples, 0 failures, 1 pending
Randomized with seed 8718
Coverage report generated for RSpec to /home/travis/build/Strech/pup/coverage. 5326 / 10697 LOC (49.79%) covered.
Coverage = 49.79%. Sending report to https://codeclimate.com for branch master... done.
```

Local: 107 / 108 LOC (99.07%) covered
Travis: 5326 / 10697 LOC (49.79%) covered

I don`t know why results so different?

**Comment by grosser** [comment]
this should do the trick: https://github.com/grosser/cc-amend

**Comment by Strech** [comment]
@grosser what's the trick? I'm asking about single run, not about multiple runs or something like that

**Comment by grosser** [comment]
whoops idk, somehow posted on wrong PR :D

**Comment by davidyin1212** [comment]
has anyone figured out this issue?

**Comment by grosser** [comment]
might be the app getting eager-loaded in dev ... try RAILS_ENV=test CI=1 rake test

**Comment by davidyin1212** [comment]
Hmm doesn't seem to work for me for some reason files are actually missing when I check the test report on code climate when compared to locally running it in SimpleCov

**Comment by dblandin** [comment]
Hey @Strech,

We've made some improvements to the ruby test reporter that should address the inconsistencies you reported.

The new version requires a different invocation style. If you have some time, you can find the upgrade documentation [here](https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions).

**Comment by Strech** [comment]
@dblandin Thanks, awesome!
