### ISSUE TITLE
please support CODE_CLIMATE_TO_FILE on top of TO_FILE

### ISSUE THREAD

**Issue by grosser** [codeclimate/ruby-test-reporter#76]
and deprecate TO_FILE later

TO_FILE is very undescriptive and might be used by some other project/thing

@calavera

**Comment by calavera** [comment]
totally agree with you, let see what @noahd1 thinks about.

**Comment by noahd1** [comment]
I'm down with that. Feel free to open a PR with that change.

**Comment by jonathancadepowers** [comment]
I'm going to go ahead and close this one out. We'd love a PR for this if possible.
