### ISSUE TITLE
Filter Not Working on Test Coverage

### ISSUE THREAD

**Issue by jclif** [codeclimate/ruby-test-reporter#88]
I have the following code set up so that I can exclude a folder from test coverage:

require 'codeclimate-test-reporter'
require 'simplecov'
SimpleCov.start do
  add_filter '/app/models/concerns/rails_admin_dsl/'
  formatter SimpleCov::Formatter::MultiFormatter[
    SimpleCov::Formatter::HTMLFormatter,
    CodeClimate::TestReporter::Formatter
  ]
end

This works locally to increase the test coverage, but the files within the filtered directory still show up on code climate.

**Comment by dimascyriaco** [comment]
I have the same problem.

**Comment by mateuszpalyz** [comment]
this works for me
```ruby
if ENV['CI']
  require 'codeclimate-test-reporter'
  SimpleCov.start 'rails' do
    formatter SimpleCov::Formatter::MultiFormatter[
      SimpleCov::Formatter::HTMLFormatter,
      CodeClimate::TestReporter::Formatter
    ]
    add_filter 'some/path'
  end
else
  require 'simplecov'
  SimpleCov.start 'rails' do
    add_filter 'some/path'
  end
end
```

**Comment by dblandin** [comment]
Hi @jclif, are you still experiencing this issue?

**Comment by dblandin** [comment]
Going to close this issue for now. Feel free to reopen if this is still an issue. Thanks!
