### ISSUE TITLE
Timeout Sending Coverage to Code Climate Fails the CI Build

### ISSUE THREAD

**Issue by pbyrne** [codeclimate/ruby-test-reporter#9]
Using 0.0.7 of codeclimate-test-reporter, one of our builds failed on Semaphore. Looking into the cause of the failure, it appears to have been because this gem timed out sending the coverage information. I would prefer that in the event of a timeout, it simply move on and not send the data at all, rather than cause the build to fail.

```
Sending report to https://codeclimate.com... 
Code Climate encountered an exception: Net::OpenTimeout
execution expired
[SNIP stack trace]
rake aborted!
Command failed with status (1)
```

**Comment by dblandin** [comment]
Going to close this issue as it seems like the fixes made around October 2014 fixed the problem. Let us know if that's not the case!

**Comment by BandanaPandey** [comment]
I am using ::
minitest 5.9.0
simplecov 0.12.0
simplecov-html 0.10.0
codeclimate-test-reporter 0.6.0
But when i try to run my testcases locally sometimes, i get the following::

**Code Climate encountered an exception: Net::OpenTimeout
Net::OpenTimeout**

Note:: I am running into this issue sometimes, not all the times when i run my testcases locally.
