### ISSUE TITLE
HTTP 500 Error when sending report to Code Climate

### ISSUE THREAD

**Issue by mdellandrea** [codeclimate/ruby-test-reporter#95]
I'm trying to generate code coverage for application that lives in a subfolder of my repository and keep getting an HTTP 500 response when the report is being sent to Code Climate.

```sh
$CODECLIMATE_REPO_TOKEN=<my_token_here> COVERAGE=1 bundle exec rspec spec/controllers
/No DRb server is running. Running in local process instead ...
I, [2015-10-13T11:53:12.037860 #13978]  INFO -- : Reporting coverage data to Code Climate.

<Doing Work Here>

Coverage = 39.78%. Sending report to https://codeclimate.com for branch master... Code Climate encountered an exception: RuntimeError
HTTP Error: 500
```

I verified using the `CODECLIMATE_TO_FILE=true` option, that the file path in the .json output matches the file path as listed on Code Climate. The subfolder is called "hr_suite". My test suite runs from "hr_suite".

My config:
```ruby
    CodeClimate::TestReporter.configure do |config|
      config.path_prefix = 'hr_suite'
      config.git_dir = '..'
    end
```

**Comment by rpond-pa** [comment]
+1

**Comment by BenHand** [comment]
+1

**Comment by alejandroereyes** [comment]
+1

**Comment by GordonDiggs** [comment]
Hey @mdellandrea! Does this happen every time you push or is it intermittent? Also, does it happen on your default branch or only on other branches? It's important to note that we only support test coverage on the default branch right now.

Additionally, what ruby version are you using?

**Comment by mdellandrea** [comment]
Hey @GordonDiggs ! This is happening everytime when I attempt to report. I was trying this with the default branch locally, prior to pushing to master (attempting to verify my config before pushing to remote). Does that matter?

Also, running 2.2.3.

**Comment by mdellandrea** [comment]
Changing the repository's directory structure resolved issue. Closing issue.
