### ISSUE TITLE
How to reset CODECLIMATE_REPO_TOKEN?

### ISSUE THREAD

**Issue by alexislefebvre** [codeclimate/ruby-test-reporter#97]
According to #34 and this [help page](http://docs.codeclimate.com/article/276-should-i-keep-my-test-coverage-token-secret) it's not a problem if CODECLIMATE_REPO_TOKEN is made public.

Due to a bad configuration of my Travis CI environment, my token is now public, so anyone can now send a code coverage report with this token. Even if the doc says that it's not a problem, I would like to be able to correct my error.

Is it possible to reset this token in order to have a new one and revoke the old token? I didn't found this option in my Code Climate settings. If it's not possible yet, what do you think about adding this feature?

**Comment by n054** [comment]
I can go to my git repo settings and regenerate and remove my tokens.

**Comment by alexislefebvre** [comment]
@n054 I don't see git repo settings in Code Climate's settings. And I don't see Code Climate in the "Webhooks & services" in the repo's GitHub settings. Can you please be more specific about the settings you're thinking about?

**Comment by n054** [comment]
@alexislefebvre when I go under profile settings menu I find aa personal token section. At top right corner I find a create new token button. In that section is a place to write token description. Will that not work?

**Comment by alexislefebvre** [comment]
@n054 I don't see anything related to token in my Code Climate settings.

**Comment by dblandin** [comment]
Hi @alexislefebvre,

You're right, we don't currently have a way through the UI on codeclimate.com to reset a repo's test coverage token. Most users on CircleCI, Travis, or other CI services will store their token within the environment (often managed through the CI repo settings), hidden from view during builds.

My advice for now would be to contact us at https://codeclimate.com/help and we can reset your token for you.

I'll leave this issue open as a feature request.

**Comment by pbrisbin** [comment]
> I'll leave this issue open as a feature request

I'm going to go ahead and close. Going via support is the recommended approach for regenerating tokens for now. We might expose this in the future in a self-service way, but tracking that work won't be done via GitHub issues on the test reporter client.

**Comment by yboulkaid** [comment]
For anyone stumbling upon this issue today, you can now reset your token via the web GUI in the Repo Setting > Test Coverage section
