### ISSUE TITLE
Coverage of Rails engine model files is not reported

### ISSUE THREAD

**Issue by lookitsatravis** [codeclimate/ruby-test-reporter#98]
This is likely related to colszowka/simplecov#434 since this gem uses Simplecov under the hood. Essentially, I know that the files are under test because I can force the specs to fail and, or remove them and see the test count go up or down. But for whatever reason, they are not included in the coverage output, and thus don't show up in the CodeClimate test coverage feed.

Project: https://codeclimate.com/github/lookitsatravis/api_guardian/coverage

Nothing in `app/models` is not visible in the list, and the same happens when I run Simplecov directly. I am opening this issue since I noticed that both projects are affected, though this one a little more indirectly. Thanks!

**Comment by davidyin1212** [comment]
I'm getting the exact same issue how did you manage to solve it?

**Comment by lookitsatravis** [comment]
@davidyin1212 - You need to make sure that you call `SimpleCov.start` BEFORE your test dummy app loads. e.g.

```rb
# spec_helper.rb
ENV['RAILS_ENV'] = 'test'
require 'simplecov'
SimpleCov.start do
  # ...
end

require File.expand_path('../dummy/config/environment.rb', __FILE__)
# ...
```

Also closing this since it's not an issue with this project.
